/* 10 - GELİR TABLOSU ÖZET */

SELECT
    SUM(CASE WHEN LEFT(p.HESAP_KODU,3) IN ('600','601','602','604','605','606','607','608','609')
             THEN CASE WHEN f.BA='2' THEN f.TUTAR ELSE -f.TUTAR END ELSE 0 END) AS BrutSatislar,
    SUM(CASE WHEN LEFT(p.HESAP_KODU,3)='610'
             THEN CASE WHEN f.BA='1' THEN f.TUTAR ELSE -f.TUTAR END ELSE 0 END) AS SatisIadeleri,
    SUM(CASE WHEN LEFT(p.HESAP_KODU,3)='611'
             THEN CASE WHEN f.BA='1' THEN f.TUTAR ELSE -f.TUTAR END ELSE 0 END) AS SatisIskontolari,
    SUM(CASE WHEN LEFT(p.HESAP_KODU,3) BETWEEN '620' AND '629'
             THEN CASE WHEN f.BA='1' THEN f.TUTAR ELSE -f.TUTAR END ELSE 0 END) AS SatislarinMaliyeti
FROM TBLMUHFIS f
JOIN TBLMUPLAN p ON f.HES_KOD = p.HESAP_KODU
WHERE f.TARIH BETWEEN {{TARIH_BAS}} AND {{TARIH_BIT}};
