/* 11 - BİLANÇO ÖZET */

SELECT
    SUM(CASE WHEN LEFT(p.HESAP_KODU,1)='1'
             THEN CASE WHEN f.BA='1' THEN f.TUTAR ELSE -f.TUTAR END ELSE 0 END) AS DonenVarliklar,
    SUM(CASE WHEN LEFT(p.HESAP_KODU,1)='2'
             THEN CASE WHEN f.BA='1' THEN f.TUTAR ELSE -f.TUTAR END ELSE 0 END) AS DuranVarliklar,
    SUM(CASE WHEN LEFT(p.HESAP_KODU,1)='3'
             THEN CASE WHEN f.BA='2' THEN f.TUTAR ELSE -f.TUTAR END ELSE 0 END) AS KisaVadeliYabanciKaynaklar,
    SUM(CASE WHEN LEFT(p.HESAP_KODU,1)='4'
             THEN CASE WHEN f.BA='2' THEN f.TUTAR ELSE -f.TUTAR END ELSE 0 END) AS UzunVadeliYabanciKaynaklar,
    SUM(CASE WHEN LEFT(p.HESAP_KODU,1)='5'
             THEN CASE WHEN f.BA='2' THEN f.TUTAR ELSE -f.TUTAR END ELSE 0 END) AS Ozkaynaklar
FROM TBLMUHFIS f
JOIN TBLMUPLAN p ON f.HES_KOD = p.HESAP_KODU
WHERE f.TARIH <= {{TARIH_BIT}};
