SELECT
    a.NETHESKODU,
    b.ACIKLAMA AS BANKA_HESABI,
    SUM(CASE WHEN a.BA='B' THEN a.TUTAR ELSE 0 END) AS BORC,
    SUM(CASE WHEN a.BA='A' THEN a.TUTAR ELSE 0 END) AS ALACAK,
    SUM(CASE WHEN a.BA='B' THEN a.TUTAR ELSE -a.TUTAR END) AS NET_BAKIYE
FROM TBLBNKHESTRA a
LEFT JOIN TBLBNKHESSABIT b ON b.NETHESKODU = a.NETHESKODU
WHERE b.HESAPTIPI = 0
GROUP BY a.NETHESKODU, b.ACIKLAMA
ORDER BY NET_BAKIYE DESC;
