SELECT
    X.SC_NO,
    X.SC_GIRTRH,
    X.VADETRH,
    X.SC_CIKTRH,
    X.SC_ODETRH,
    X.KAYITTARIHI,
    X.SC_VERENK,
    B.CARI_KOD,
    B.CARI_ISIM,
    X.SC_ABORCLU,
    X.YERI AS BANKASI,
    X.CEKSERI,
    X.SC_VERILENK AS BANKA_HESAP_KODU,
    K.BANKAADI     AS "VERILEN BANKA",
    X.DOVTUT,
    X.DOVTIP,
    CASE WHEN X.DOVTIP = 0 THEN 1 ELSE X.KUR END AS KUR,
    X.TUTAR
FROM TBLMCEK X
INNER JOIN TBLCASABIT B      ON X.SC_VERENK = B.CARI_KOD
LEFT JOIN TBLBNKHESSABIT H   ON H.NETHESKODU = X.SC_VERILENK
LEFT JOIN TBLBNKSABIT    K   ON K.NETBANKAKODU = H.NETBANKAKODU
WHERE X.SC_SONDUR = 'B'
  AND X.SC_YERI   = 'T'
ORDER BY X.VADETRH;
