SELECT
    X.SC_NO,
    X.SC_GIRTRH,
    X.VADETRH,
    X.SC_CIKTRH,
    X.SC_ODETRH,
    X.KAYITTARIHI,
    X.SC_VERENK,
    B.CARI_ISIM,
    X.SC_VERILENK,
    C.CARI_ISIM AS CIRO_EDILEN_CARI,
    X.YERI AS BANKASI,
    X.CEKSERI,
    X.DOVTUT,
    X.DOVTIP,
    CASE WHEN X.DOVTIP = 0 THEN 1 ELSE X.KUR END AS KUR,
    X.TUTAR
FROM TBLMCEK X
INNER JOIN TBLCASABIT B ON X.SC_VERENK   = B.CARI_KOD
INNER JOIN TBLCASABIT C ON X.SC_VERILENK = C.CARI_KOD
WHERE X.SC_SONDUR = 'B'
  AND X.SC_YERI   = 'C'
ORDER BY X.VADETRH;
