SELECT 
    a.SC_NO,
    a.VADETRH,
    a.SC_VERENK,
    b.CARI_ISIM AS VEREN_CARI,
    a.SC_VERILENK,
    c.CARI_ISIM AS CIRO_EDILEN_CARI,
    a.TUTAR
FROM TBLMCEK a
JOIN TBLCASABIT b ON b.CARI_KOD = a.SC_VERENK
JOIN TBLCASABIT c ON c.CARI_KOD = a.SC_VERILENK
WHERE a.SC_SONDUR = 'B'
  AND a.SC_YERI   = 'C'
ORDER BY a.VADETRH;
