SELECT 
    a.SC_NO,
    a.VADETRH,
    a.SC_VERENK,
    b.CARI_ISIM,
    a.SC_ODETRH,
    a.TUTAR
FROM TBLMCEK a
JOIN TBLCASABIT b ON b.CARI_KOD = a.SC_VERENK
WHERE a.SC_YERI = 'I'
ORDER BY a.VADETRH;
