SELECT
    X.SC_NO,
    X.SC_GIRTRH,
    X.VADETRH,
    X.SC_CIKTRH,
    X.SC_ODETRH,
    X.KAYITTARIHI,
    C.CARI_KOD,
    C.CARI_ISIM,
    X.YERI AS BANKASI,
    X.CEKSERI,
    X.DOVTUT,
    X.DOVTIP,
    CASE WHEN X.DOVTIP = 0 THEN 1 ELSE X.KUR END AS KUR,
    X.TUTAR
FROM TBLBCEK X
LEFT JOIN TBLCASABIT C ON C.CARI_KOD = X.SC_VERILENK
WHERE X.SC_SONDUR = 'O'
ORDER BY X.SC_ODETRH;
