SELECT 
    b.SC_NO,
    b.VADETRH,
    c.CARI_ISIM,
    b.YERI,
    b.SC_ODETRH,
    b.TUTAR
FROM TBLBCEK b
LEFT JOIN TBLCASABIT c ON c.CARI_KOD = b.SC_VERILENK
WHERE b.SC_SONDUR = 'O'
ORDER BY b.SC_ODETRH;
