SELECT 
    b.SC_NO,
    b.VADETRH,
    c.CARI_ISIM,
    b.YERI,
    b.TUTAR
FROM TBLBCEK b
LEFT JOIN TBLCASABIT c ON c.CARI_KOD = b.SC_VERILENK
WHERE b.SC_SONDUR NOT IN ('B','O')
ORDER BY b.VADETRH;
