
SELECT
    B.RAPORKODU,
    B.NETHESKODU,
    B.ACIKLAMA,
    B.DOVIZTIPI,
    SUM(B.HESBORCTOP)                         AS TOPLAM_BORC_TRY,
    SUM(B.HESALACTOP)                         AS TOPLAM_ALACAK_TRY,
    SUM(B.HESBORCTOP - B.HESALACTOP)           AS BAKIYE_TRY,
    SUM(B.HESBORCTOPDOV)                       AS TOPLAM_BORC_DOV,
    SUM(B.HESALACTOPDOV)                       AS TOPLAM_ALACAK_DOV,
    SUM(B.HESBORCTOPDOV - B.HESALACTOPDOV)     AS DOVIZ_BAKIYE
FROM TBLBNKHESSABIT B
WHERE
(
       B.NETHESKODU LIKE '102%'
    OR B.NETHESKODU LIKE '300%'
    OR B.NETHESKODU LIKE '301%'
    OR B.NETHESKODU LIKE '302%'
    OR B.NETHESKODU LIKE '400%'
    OR B.NETHESKODU LIKE '401%'
    OR B.NETHESKODU LIKE '402%'
)
GROUP BY
    B.RAPORKODU,
    B.NETHESKODU,
    B.ACIKLAMA,
    B.DOVIZTIPI
ORDER BY
    B.NETHESKODU;
