SELECT
    f.TARIH,
    f.FISNO,
    f.HES_KOD,
    f.HESAPISMI,
    CASE f.BA WHEN 1 THEN 'BORÇ' ELSE 'ALACAK' END AS BA_TIPI,
    f.TUTAR,
    f.ACIKLAMA,
    f.REF_KOD
FROM TBLMUHFIS f
WHERE f.REF_KOD IS NULL
ORDER BY f.TARIH DESC;
