SELECT
    c.SC_NO,
    c.VADETRH,
    c.SC_VERENK,
    k.CARI_ISIM,
    c.TUTAR
FROM TBLMCEK c
JOIN TBLCASABIT k ON k.CARI_KOD = c.SC_VERENK
WHERE c.SC_SONDUR = 'B'
  AND c.SC_YERI   = 'P'
ORDER BY c.VADETRH;
