/* 06 - TOPLAM STOK MALİYETİ (Döviz Tipi Bazlı) */

SELECT
    CASE WHEN a.ALIS_DOV_TIP=0 THEN 'TRY'
         WHEN a.ALIS_DOV_TIP=1 THEN 'USD'
         WHEN a.ALIS_DOV_TIP=2 THEN 'EUR'
         ELSE 'Bilinmiyor' END AS [Döviz Tipi],
    SUM(ISNULL(p.STOK_MIKTARI,0) * ISNULL(a.DOV_MAL_FIAT,0)) AS [Toplam Maliyet]
FROM TBLSTSABIT a
LEFT JOIN (
    SELECT
        STOK_KODU,
        SUM(TOP_GIRIS_MIK) - SUM(TOP_CIKIS_MIK) AS STOK_MIKTARI
    FROM TBLSTOKPH
    GROUP BY STOK_KODU
) p ON a.STOK_KODU = p.STOK_KODU
GROUP BY
    CASE WHEN a.ALIS_DOV_TIP=0 THEN 'TRY'
         WHEN a.ALIS_DOV_TIP=1 THEN 'USD'
         WHEN a.ALIS_DOV_TIP=2 THEN 'EUR'
         ELSE 'Bilinmiyor' END;
