SELECT
    s.SERI_NO,
    s.STOK_KODU,
    s.BELGENO,
    CAST(h.STHAR_NF * (1 + h.STHAR_KDV/100.0) AS decimal(18,2)) AS TL_FIYAT,
    CAST(h.STHAR_DOVFIAT * (1 + h.STHAR_KDV/100.0) AS decimal(18,2)) AS DOVIZ_FIYAT,
    h.STHAR_DOVTIP
FROM TBLSERITRA s
LEFT JOIN TBLSTHAR h ON h.INCKEYNO = s.STRA_INC
WHERE s.GCKOD = 'G';
