SELECT
    s.SERI_NO,
    s.STOK_KODU,
    st.STOK_ADI,
    CAST(s.TARIH AS date) AS TARIH,
    s.BELGENO,
    s.HARACIK AS CARI_KOD,
    c.CARI_ISIM AS CARI_ADI,
    s.DEPOKOD,
    s.GCKOD
FROM TBLSERITRA s
INNER JOIN TBLSTSABIT st ON st.STOK_KODU = s.STOK_KODU
LEFT JOIN TBLCASABIT c ON c.CARI_KOD = s.HARACIK
WHERE s.GCKOD = 'G'
ORDER BY s.TARIH DESC, s.BELGENO;
