/* 01 - STOK KARTLARI: Alış/Satış hareket var mı + Grup/Kod doluluk (2 VT) */

WITH STOKLAR AS (
    SELECT
        '{{SIRKET_A}}' AS SIRKET,
        STOK_KODU,
        STOK_ADI,
        OLCU_BR1,
        GRUP_KODU,
        KOD_1,
        KOD_2,
        KOD_3
    FROM {{VT_A}}.dbo.TBLSTSABIT

    UNION ALL

    SELECT
        '{{SIRKET_B}}' AS SIRKET,
        STOK_KODU,
        STOK_ADI,
        OLCU_BR1,
        NULL AS GRUP_KODU,
        NULL AS KOD_1,
        NULL AS KOD_2,
        NULL AS KOD_3
    FROM {{VT_B}}.dbo.TBLSTSABIT
),
HAREKETLER AS (
    SELECT '{{SIRKET_A}}' AS SIRKET, 'ALIS' AS HAREKET_TIPI, STOK_KODU
    FROM {{VT_A}}.dbo.TBLSTHAR
    WHERE STHAR_HTUR='J' AND STHAR_GCKOD='G' AND YEAR(STHAR_TARIH)={{YIL}}

    UNION ALL
    SELECT '{{SIRKET_B}}', 'ALIS', STOK_KODU
    FROM {{VT_B}}.dbo.TBLSTHAR
    WHERE STHAR_HTUR='J' AND STHAR_GCKOD='G' AND YEAR(STHAR_TARIH)={{YIL}}

    UNION ALL
    SELECT '{{SIRKET_A}}', 'SATIS', STOK_KODU
    FROM {{VT_A}}.dbo.TBLSTHAR
    WHERE STHAR_HTUR='J' AND STHAR_GCKOD='C' AND YEAR(STHAR_TARIH)={{YIL}}

    UNION ALL
    SELECT '{{SIRKET_B}}', 'SATIS', STOK_KODU
    FROM {{VT_B}}.dbo.TBLSTHAR
    WHERE STHAR_HTUR='J' AND STHAR_GCKOD='C' AND YEAR(STHAR_TARIH)={{YIL}}
)
SELECT
    s.SIRKET,
    s.STOK_KODU,
    tek.KULL8S AS ERP_STOK_KODU,
    s.STOK_ADI AS STOK_TANIMI,
    s.OLCU_BR1 AS OLCU_BIRIMI,

    CASE WHEN SUM(CASE WHEN h.HAREKET_TIPI='ALIS'  THEN 1 ELSE 0 END) > 0 THEN 'VAR' ELSE 'YOK' END AS ALIS_VAR_MI,
    CASE WHEN SUM(CASE WHEN h.HAREKET_TIPI='SATIS' THEN 1 ELSE 0 END) > 0 THEN 'VAR' ELSE 'YOK' END AS SATIS_VAR_MI,

    CASE WHEN g.GRUP_KOD IS NOT NULL THEN 'VAR' ELSE 'YOK' END AS ANA_GRUP_DOLU_MU,
    CASE WHEN k1.GRUP_KOD IS NOT NULL THEN 'VAR' ELSE 'YOK' END AS KOD1_DOLU_MU,
    CASE WHEN k2.GRUP_KOD IS NOT NULL THEN 'VAR' ELSE 'YOK' END AS KOD2_DOLU_MU,
    CASE WHEN k3.GRUP_KOD IS NOT NULL THEN 'VAR' ELSE 'YOK' END AS KOD3_DOLU_MU,

    g.GRUP_KOD  AS ANA_GRUP_KOD,
    g.GRUP_ISIM AS ANA_GRUP_AD,
    k1.GRUP_KOD AS KOD1_KOD,
    k1.GRUP_ISIM AS KOD1_AD,
    k2.GRUP_KOD AS KOD2_KOD,
    k2.GRUP_ISIM AS KOD2_AD,
    k3.GRUP_KOD AS KOD3_KOD,
    k3.GRUP_ISIM AS KOD3_AD
FROM STOKLAR s
LEFT JOIN {{VT_A}}.dbo.TBLSTSABITEK tek ON tek.STOK_KODU = s.STOK_KODU

-- Kod referansı VT_A üzerinden (genel kullanım için)
LEFT JOIN {{VT_A}}.dbo.TBLSTSABIT ref ON ref.STOK_KODU = s.STOK_KODU
LEFT JOIN {{VT_A}}.dbo.TBLSTGRUP   g   ON ref.GRUP_KODU = g.GRUP_KOD
LEFT JOIN {{VT_A}}.dbo.TBLSTOKKOD1 k1  ON ref.KOD_1 = k1.GRUP_KOD
LEFT JOIN {{VT_A}}.dbo.TBLSTOKKOD2 k2  ON ref.KOD_2 = k2.GRUP_KOD
LEFT JOIN {{VT_A}}.dbo.TBLSTOKKOD3 k3  ON ref.KOD_3 = k3.GRUP_KOD

LEFT JOIN HAREKETLER h ON h.STOK_KODU = s.STOK_KODU AND h.SIRKET = s.SIRKET
GROUP BY
    s.SIRKET, s.STOK_KODU, s.STOK_ADI, s.OLCU_BR1, tek.KULL8S,
    g.GRUP_KOD, g.GRUP_ISIM,
    k1.GRUP_KOD, k1.GRUP_ISIM,
    k2.GRUP_KOD, k2.GRUP_ISIM,
    k3.GRUP_KOD, k3.GRUP_ISIM
ORDER BY s.SIRKET, s.STOK_KODU;
