/* 02 - HAREKETİ OLAN CARİLER (2 VT) */

SELECT
    '{{SIRKET_A}}' AS SIRKET,
    c.CARI_KOD,
    c.CARI_ISIM AS CARI_TANIMI,
    c.GRUP_KODU,
    c.ULKE_KODU,
    c.CARI_TIP,
    tek.S_YEDEK2 AS ANA_CARI_KOD
FROM {{VT_A}}.dbo.TBLCASABIT c
LEFT JOIN {{VT_A}}.dbo.TBLCASABITEK tek ON tek.CARI_KOD = c.CARI_KOD
WHERE EXISTS (
    SELECT 1
    FROM {{VT_A}}.dbo.TBLSTHAR s
    WHERE s.STHAR_CARIKOD = c.CARI_KOD
      AND s.STHAR_GCKOD IN ('G','C')
      AND s.STHAR_HTUR  IN ('J','L')
)

UNION ALL

SELECT
    '{{SIRKET_B}}',
    c.CARI_KOD,
    c.CARI_ISIM,
    c.GRUP_KODU,
    c.ULKE_KODU,
    c.CARI_TIP,
    tek.S_YEDEK2
FROM {{VT_B}}.dbo.TBLCASABIT c
LEFT JOIN {{VT_B}}.dbo.TBLCASABITEK tek ON tek.CARI_KOD = c.CARI_KOD
WHERE EXISTS (
    SELECT 1
    FROM {{VT_B}}.dbo.TBLSTHAR s
    WHERE s.STHAR_CARIKOD = c.CARI_KOD
      AND s.STHAR_GCKOD IN ('G','C')
      AND s.STHAR_HTUR  IN ('J','L')
)
ORDER BY GRUP_KODU, ULKE_KODU, CARI_TANIMI, SIRKET, CARI_KOD;
