/* 03 - CARİ KARTLARI: Üst Kod Eşlemesi (mevcut VT) */

SELECT
    c.CARI_KOD AS KOD,
    c.CARI_ISIM AS AD,
    c.GRUP_KODU AS GRUP,
    c.ULKE_KODU AS ULKE,
    c.CARI_TIP AS TIP,
    tek.S_YEDEK2 AS UST_KOD
FROM TBLCASABIT c
LEFT JOIN TBLCASABITEK tek ON tek.CARI_KOD = c.CARI_KOD
ORDER BY c.GRUP_KODU, c.ULKE_KODU, c.CARI_ISIM, c.CARI_KOD;
