/* 04 - STOK GRUP / KOD HİYERARŞİSİ (mevcut VT) */

SELECT DISTINCT
    RTRIM(LTRIM(g.GRUP_KOD)) AS ANA_GRUP_KOD,
    g.GRUP_ISIM AS ANA_GRUP_AD,
    RTRIM(LTRIM(k1.GRUP_KOD)) AS KOD1_KOD,
    k1.GRUP_ISIM AS KOD1_AD,
    RTRIM(LTRIM(k2.GRUP_KOD)) AS KOD2_KOD,
    k2.GRUP_ISIM AS KOD2_AD,
    RTRIM(LTRIM(k3.GRUP_KOD)) AS KOD3_KOD,
    k3.GRUP_ISIM AS KOD3_AD
FROM TBLSTGRUP g
LEFT JOIN TBLSTOKKOD1 k1 ON RTRIM(LTRIM(k1.KAYITYAPANKUL)) = RTRIM(LTRIM(g.GRUP_KOD))
LEFT JOIN TBLSTOKKOD2 k2 ON RTRIM(LTRIM(k2.KAYITYAPANKUL)) = RTRIM(LTRIM(k1.GRUP_KOD))
LEFT JOIN TBLSTOKKOD3 k3 ON RTRIM(LTRIM(k3.KAYITYAPANKUL)) = RTRIM(LTRIM(k2.GRUP_KOD))
WHERE g.GRUP_KOD IS NOT NULL
ORDER BY ANA_GRUP_KOD, KOD1_KOD, KOD2_KOD, KOD3_KOD;
