SELECT 
    a.STOK_KODU,
    b.STOK_ADI,
    (a.TOP_GIRIS_MIK - a.TOP_CIKIS_MIK) AS BAKIYE_MIKTAR,
    a.SON_GIR_NET_FIAT,
    CAST((a.TOP_GIRIS_MIK - a.TOP_CIKIS_MIK) * a.SON_GIR_NET_FIAT AS decimal(18,2)) AS NET_MALIYET,
    b.SATIS_FIAT1,
    CAST((a.TOP_GIRIS_MIK - a.TOP_CIKIS_MIK) * b.SATIS_FIAT1 AS decimal(18,2)) AS SATIS_MALIYETI
FROM TBLSTOKPH a
JOIN TBLSTSABIT b ON b.STOK_KODU = a.STOK_KODU;
