SELECT
    h.CARI_KOD,
    c.CARI_ISIM,
    SUM(h.BORC)   AS BORC,
    SUM(h.ALACAK) AS ALACAK,
    SUM(h.BORC - h.ALACAK) AS NET_BAKIYE
FROM TBLCAHAR h
JOIN TBLCASABIT c ON c.CARI_KOD = h.CARI_KOD
WHERE c.CARI_TIP = 'S'
GROUP BY h.CARI_KOD, c.CARI_ISIM
ORDER BY NET_BAKIYE DESC;
